#version 450

// #define HAS_SUBGROUP_ARITHMETIC

#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_buffer_reference: require
#extension GL_EXT_buffer_reference2: require

#extension GL_KHR_shader_subgroup_vote: enable
#extension GL_KHR_shader_subgroup_ballot: enable
#extension GL_KHR_shader_subgroup_shuffle: enable
#extension GL_KHR_shader_subgroup_shuffle_relative: enable

#ifdef HAS_SUBGROUP_ARITHMETIC
#extension GL_KHR_shader_subgroup_arithmetic: enable
#endif


#define SUBGROUP_SIZE  32
#define NUM_SUBGROUPS  8
#define WORKGROUP_SIZE (SUBGROUP_SIZE * NUM_SUBGROUPS)

layout(local_size_x = WORKGROUP_SIZE) in;

layout(buffer_reference, buffer_reference_align = 1) buffer u8buf {
    uint8_t v;
};

layout(buffer_reference, buffer_reference_align = 4) buffer u32buf {
    uint32_t v;
};

layout(buffer_reference, buffer_reference_align = 8) volatile buffer vu64buf {
    uint64_t v;
};

layout(push_constant) uniform pushConstants {
    u8buf   inbuf;
    u8buf   flagbuf;
    u32buf  outbuf;
    vu64buf tmpbuf;

    uint32_t init_val;
    uint array_size;
};

#define STATUS_INVALID   uint32_t(0)
#define STATUS_AGGREGATE uint32_t(1)
#define STATUS_PREFIX    uint32_t(2)

shared uint32_t subgroup_partials[NUM_SUBGROUPS];
shared bool subgroup_partials_flags[NUM_SUBGROUPS];

uint64_t pack64(uint32_t x, uint32_t y) {
    return (uint64_t(x) << 32) | (uint64_t(y) << 0);
}

uint32_t subgroup_reduce_sum(uint32_t v) {
#ifdef HAS_SUBGROUP_ARITHMETIC
    return subgroupAdd(v);
#else
    for (uint mask = gl_SubgroupSize >> 1; mask > 0; mask >>= 1) {
        v += subgroupShuffleXor(v, mask);
    }
    return v;
#endif
}

int subgroup_reduce_min(int v) {
#ifdef HAS_SUBGROUP_ARITHMETIC
    return subgroupMin(v);
#else
    for (uint mask = gl_SubgroupSize >> 1; mask > 0; mask >>= 1) {
        v = min(subgroupShuffleXor(v, mask), v);
    }
    return v;
#endif
}

int subgroup_reduce_max(int v) {
#ifdef HAS_SUBGROUP_ARITHMETIC
    return subgroupMax(v);
#else
    for (uint mask = gl_SubgroupSize >> 1; mask > 0; mask >>= 1) {
        v = max(subgroupShuffleXor(v, mask), v);
    }
    return v;
#endif
}

uint32_t subgroup_inclusive_add_with_flag(uint32_t v, inout bool f) {
    for (uint offset = 1; offset < gl_SubgroupSize; offset <<= 1) {
        uint32_t sv = subgroupShuffleUp(v, offset);
        bool     sf = subgroupShuffleUp(f, offset);
        if (gl_SubgroupInvocationID >= offset)
            v += (!f ? sv : 0), f = f || sf;
    }
    return v;
}

uint32_t subgroup_exclusive_add_with_flag(uint32_t v, inout bool f) {
    return subgroup_inclusive_add_with_flag(v, f) - v;
}

uint32_t workgroup_reduce_sum(uint32_t v) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID,
        ssz = gl_SubgroupSize, nsg = gl_NumSubgroups;

    uint32_t s = subgroup_reduce_sum(v);
    if (subgroupElect())
        subgroup_partials[sid] = uint(s);
    barrier();

    uint32_t tmp = (siid < nsg) ? subgroup_partials[siid] : 0;
    barrier();

    return subgroup_reduce_sum(tmp);
}

uint32_t workgroup_inclusive_add_with_flag(uint32_t v, inout bool f) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID, ssz = gl_SubgroupSize;

    uint32_t a = subgroup_inclusive_add_with_flag(v, f);
    if (siid == ssz - 1)
        subgroup_partials[sid] = a, subgroup_partials_flags[sid] = f;
    barrier();

    uint32_t tmp1 = (siid < sid) ? subgroup_partials      [siid] : 0;
    bool     tmp2 = (siid < sid) ? subgroup_partials_flags[siid] : false;
    barrier();

    int lane = int(subgroupBallotFindMSB(subgroupBallot((siid < sid) ? tmp2 : false)));
    uint32_t s = subgroup_reduce_sum((lane <= int(siid) && siid < sid) ? tmp1 : 0);
    return a + (!f ? s : 0);
}

bool workgroup_any(bool pred) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID,
        ssz = gl_SubgroupSize, nsg = gl_NumSubgroups;

    bool r = subgroupAny(pred);
    if (subgroupElect())
        subgroup_partials[sid] = uint(r);
    barrier();

    uint32_t tmp = (siid < nsg) ? subgroup_partials[siid] : 0;
    barrier();

    return subgroupAny(tmp == uint(true));
}

bool workgroup_all(bool pred) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID,
        ssz = gl_SubgroupSize, nsg = gl_NumSubgroups;

    bool r = subgroupAll(pred);
    if (subgroupElect())
        subgroup_partials[sid] = uint(r);
    barrier();

    uint32_t tmp = (siid < nsg) ? subgroup_partials[siid] : 1;
    barrier();

    return subgroupAll(tmp == uint(true));
}

int workgroup_ballot_min_lane(bool pred) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID,
        ssz = gl_SubgroupSize, nsg = gl_NumSubgroups;

    uint lane = subgroupBallotFindLSB(subgroupBallot(pred));
    if (subgroupElect())
        subgroup_partials[sid] = lane + ((int(lane) >= 0) ? sid * ssz : 0);
    barrier();

    int tmp = (siid < nsg) ? int(subgroup_partials[siid]) : 0x7fffffff;
    barrier();

    return subgroup_reduce_min(tmp);
}

int workgroup_ballot_max_lane(bool pred) {
    uint siid = gl_SubgroupInvocationID, sid = gl_SubgroupID,
        ssz = gl_SubgroupSize, nsg = gl_NumSubgroups;

    uint lane = subgroupBallotFindMSB(subgroupBallot(pred));
    if (subgroupElect())
        subgroup_partials[sid] = lane + ((int(lane) >= 0) ? sid * ssz : 0);
    barrier();

    int tmp = (siid < nsg) ? int(subgroup_partials[siid]) : -0x80000000;
    barrier();

    return subgroup_reduce_max(tmp);
}

void main() {
    uint lid = gl_LocalInvocationID.x, wid = gl_WorkGroupID.x, gid = gl_GlobalInvocationID.x,
        wsz = gl_WorkGroupSize.x;

    uint32_t val;
    bool flag;

    if (gid < array_size)
        val = inbuf[gid].v, flag = flagbuf[gid].v != 0;
    else
        val = 0, flag = false;

    if (gid == 0)
        val += init_val;

    // Workgroup prefix sum
    val = workgroup_inclusive_add_with_flag(val, flag);

    // Propagate flag to upper lanes
    int lane = workgroup_ballot_min_lane(flag);
    if (lane >= 0 && lid >= lane)
        flag = true;

    uint32_t prefix = 0;
    if (wid != 0) {
        // Publish aggregate sum
        if (lid == wsz - 1) {
            tmpbuf[wid].v = pack64(val, flag ? STATUS_PREFIX : STATUS_AGGREGATE);
            memoryBarrierBuffer();
        }

        // Synchronize with memory barrier return, which is when
        // we expect records from other workgroups to arrive
        barrier();

        // Decoupled lookback
        int status_pos = int(wid + lid - wsz);
        while (true) {
            memoryBarrierBuffer();
            uint64_t status;
            if (status_pos >= 0)
                status = tmpbuf[status_pos].v;
            else
                status = pack64(0, STATUS_AGGREGATE);

            uint32_t s = uint32_t(status), v = uint32_t(status >> 32);
            if (workgroup_any(s == STATUS_INVALID)) {
                continue;
            } else if (workgroup_all(s == STATUS_AGGREGATE)) {
                prefix     += workgroup_reduce_sum(v);
                status_pos -= int(wsz);
            } else {
                lane = max(0, workgroup_ballot_max_lane(s == STATUS_PREFIX));
                uint32_t s = workgroup_reduce_sum((lid >= lane) ? v : 0);

                prefix += !flag ? s : 0;
                break;
            }
        }
    }

    // Publish full prefix
    if (lid == wsz - 1) {
        tmpbuf[wid].v = pack64(prefix + val, STATUS_PREFIX);
        memoryBarrierBuffer();
    }

    // Write out result
    if (gid < array_size)
        outbuf[gid].v = uint(prefix + val);
}
